//week10-2
PImage postman,head,body,arm1,arm2,hand1,hand2,lag1,lag2;
void setup(){
  size(500,560);
  postman=loadImage("postman.png");
  head=loadImage("head.png");
  body=loadImage("body.png");
  arm1=loadImage("arm1.png");
  arm2=loadImage("arm2.png");
  hand1=loadImage("hand1.png");
  hand2=loadImage("hand2.png");
  lag1=loadImage("lag1.png");
  lag2=loadImage("lag2.png");
}
void draw(){
  background(#FFFFF2);
  image(postman,0,0);//全身
  fill(255,0,255,128);//半透明紫色
  rect(0,0,560,560);//蓋上去
   pushMatrix();
    translate(113,192);
    //rotate(radians(mouseX));
    translate(-113,-192);  
    image(arm1,0,0);
  popMatrix();
  pushMatrix();
    translate(168,192);
    //rotate(radians(mouseX));
    translate(-168,-192);  
    image(arm2,0,0);
  popMatrix();
  pushMatrix();
    translate(67,191);
    rotate(radians(mouseX));
    translate(-67,-191);  
    image(hand1,0,0);
  popMatrix();
  pushMatrix();
    translate(208,189);
    rotate(radians(mouseX));
    translate(-208,-189);  
    image(hand2,0,0);
  popMatrix();  
  pushMatrix();
    translate(112,182);
    //rotate(radians(mouseX));
    translate(-112,-182);  
    image(head,0,0);//先畫頭
  popMatrix();
   pushMatrix();
    translate(133,273);
    rotate(radians(mouseX));
    translate(-133,-273);  
    image(lag1,0,0);
  popMatrix();
   pushMatrix();
    translate(152,273);
    //rotate(radians(mouseX));
    translate(-152,-273);  
    image(lag2,0,0);
  popMatrix();
    image(body,0,0);//在畫身體   
}
